### ISSUE TITLE
Add CI support for tests

### ISSUE THREAD

**Issue by johncblandii** [lucasbento/react-native-thumbnail-video#10]
Once #5 goes through, we need to add in CI support; Travis, CircleCI, or whatever.

**Comment by lucasbento** [comment]
Nice, thanks for the issue, @johncblandii!

Also thanks for the work in #5, just invited you to be a contributor!

I'll setup Travis CI asap.

**Comment by lucasbento** [comment]
@johncblandii: can you check #11? I can't add you as a reviewer yet.

**Comment by johncblandii** [comment]
Great on Travis and awesome on being a contributor. I appreciate it.
