### ISSUE TITLE
Does not function well in List. Less than half display.

### ISSUE THREAD

**Issue by hindsricardo** [lucasbento/react-native-thumbnail-video#12]
I am displaying a list of items with YouTube URLs and using this package to generate an image for each. The images do not display for most of the urls. In a list of 10 only 4 display. Out of 26 only 3 display. It seems very sporadic.

**Comment by lucasbento** [comment]
@hindsricardo: thanks for opening an issue, can you provide a running snippet of your code (it will be much easier if you use https://snack.expo.io)?

**Comment by johncblandii** [comment]
@hindsricardo are you setting a unique id on the list?

Seeing some code would definitely help.

**Comment by lucasbento** [comment]
Closing this since it's been a while without any response.
