### ISSUE TITLE
Hide Play Button

### ISSUE THREAD

**Issue by haideralishah** [lucasbento/react-native-thumbnail-video#13]
I want to hide play button from thumbnail and only want to see the image. How can I do this?

**Comment by haideralishah** [comment]
I just resolve it myself by putting opacity: 0 in iconStyle.

<Thumbnail url={this.props.sourceProp} imageWidth={'100%'} imageHeight={'100%'} iconStyle={{ opacity: 0 }} />

**Comment by lucasbento** [comment]
Hey @haideralishah, I agree that there should be a better way to hide the play button, something like `<Thumbnail showIcon={false} />`, I would appreciate very much a PR implementing this.

**Comment by lucasbento** [comment]
Fixed by @leksyib on #15, thank you again, @leksyib!
