### ISSUE TITLE
Invariant violation Error when running > 0.0.8

### ISSUE THREAD

**Issue by karanmartian** [lucasbento/react-native-thumbnail-video#19]
Hi,

I am on Expo SDK 29 and:

"react": "16.3.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",

I keep getting invariant violation error ...... you likely forgot to export your component when running version 0.1.0 and 0.1.1. The exact same code works fine when running on v0.0.8.

Any thoughts?

**Comment by lucasbento** [comment]
Hi @karanmartian, would you be able to tell me if it works if you try `import { Thumbnail } from 'react-native-thumbnail-video';` instead of `import Thumbnail...`?

**Comment by karanmartian** [comment]
yes that did the trick. Thanks @lucasbento. I think the repo README shud be updated too.

**Comment by lucasbento** [comment]
@karanmartian: cool, already did so on #20, gonna merge it, thanks!
